language: python
python:
  "3.6"

before_install:
  - nvm install stable
  - nvm use stable
  - pip install -r requirements.txt
  - pip install pytest-sugar

script:
  - make
  - make test

deploy:
  skip_cleanup: true
  provider: script
  script: python src/upload.py
  on:
    branch: main
