dist: trusty
sudo: required

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start

addons:
  chrome: stable

# Handle git submodules yourself
git:
    submodules: false

language: python
python:
  "3.6"

before_install:
    # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - nvm install stable
  - nvm use stable
  - pip install -r requirements.txt
  - # start application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &


script:
  - make
  - python bin/gen_volume.py 19
  - make test

deploy:
  skip_cleanup: true
  provider: script
  script: python bin/upload.py
  on:
    branch: master
